import { Player } from './types';

export const INITIAL_PLAYERS: Player[] = [
  {
    id: "v-kohli",
    name: "Virat Kohli",
    team: "India",
    role: "allrounder",
    style: "Right-hand Bat",
    type: "batsman",
    matches: [
      { id: "m1", opponent: "Pakistan", date: "2024-10-23", matchType: "T20", runs: 82, balls: 53, fours: 6, sixes: 4, dismissed: false },
      { id: "m2", opponent: "England", date: "2024-11-10", matchType: "T20", runs: 51, balls: 36, fours: 4, sixes: 1, dismissed: true },
      { id: "m3", opponent: "New Zealand", date: "2025-01-18", matchType: "ODI", runs: 95, balls: 104, fours: 8, sixes: 2, dismissed: true },
      { id: "m4", opponent: "South Africa", date: "2025-02-05", matchType: "ODI", runs: 12, balls: 18, fours: 1, sixes: 0, dismissed: true },
      { id: "m5", opponent: "Australia", date: "2025-03-24", matchType: "Test", runs: 101, balls: 121, fours: 10, sixes: 0, dismissed: false },
    ],
    shots: [
      { id: "s1", angle: 45, distance: 0.75, runs: 4, shotType: "Drive" },
      { id: "s2", angle: 25, distance: 0.90, runs: 6, shotType: "Drive" },
      { id: "s3", angle: 135, distance: 0.65, runs: 1, shotType: "Cut" },
      { id: "s4", angle: 220, distance: 0.85, runs: 4, shotType: "Flick" },
      { id: "s5", angle: 315, distance: 0.92, runs: 6, shotType: "Pull" },
      { id: "s6", angle: 270, distance: 0.80, runs: 4, shotType: "Pull" },
      { id: "s7", angle: 10, distance: 0.98, runs: 6, shotType: "Drive" },
      { id: "s8", angle: 90, distance: 0.55, runs: 2, shotType: "Drive" },
      { id: "s9", angle: 300, distance: 0.40, runs: 1, shotType: "Flick" },
      { id: "s10", angle: 110, distance: 0.80, runs: 4, shotType: "Cut" },
      { id: "s11", angle: 180, distance: 0.30, runs: 0, shotType: "Defensive" },
      { id: "s12", angle: 15, distance: 0.88, runs: 4, shotType: "Drive" },
    ],
    deliveries: []
  },
  {
    id: "r-sharma",
    name: "Rohit Sharma",
    team: "India",
    role: "batsman",
    style: "Right-hand Bat",
    type: "batsman",
    matches: [
      { id: "m11", opponent: "Australia", date: "2024-11-15", matchType: "T20", runs: 47, balls: 29, fours: 5, sixes: 3, dismissed: true },
      { id: "m12", opponent: "Afghanistan", date: "2024-12-11", matchType: "ODI", runs: 131, balls: 84, fours: 16, sixes: 5, dismissed: true },
      { id: "m13", opponent: "Pakistan", date: "2025-01-20", matchType: "ODI", runs: 86, balls: 63, fours: 6, sixes: 6, dismissed: false },
      { id: "m14", opponent: "New Zealand", date: "2025-02-14", matchType: "Test", runs: 4, balls: 7, fours: 0, sixes: 0, dismissed: true },
      { id: "m15", opponent: "England", date: "2025-04-02", matchType: "T20", runs: 40, balls: 24, fours: 3, sixes: 2, dismissed: true },
    ],
    shots: [
      { id: "rs1", angle: 310, distance: 0.96, runs: 6, shotType: "Pull" },
      { id: "rs2", angle: 320, distance: 0.98, runs: 6, shotType: "Pull" },
      { id: "rs3", angle: 45, distance: 0.72, runs: 4, shotType: "Drive" },
      { id: "rs4", angle: 15, distance: 0.85, runs: 4, shotType: "Drive" },
      { id: "rs5", angle: 135, distance: 0.95, runs: 4, shotType: "Cut" },
      { id: "rs6", angle: 270, distance: 0.90, runs: 4, shotType: "Flick" },
      { id: "rs7", angle: 290, distance: 0.45, runs: 1, shotType: "Flick" },
      { id: "rs8", angle: 15, distance: 0.99, runs: 6, shotType: "Slog" },
      { id: "rs9", angle: 75, distance: 0.90, runs: 6, shotType: "Slog" },
      { id: "rs10", angle: 200, distance: 0.35, runs: 0, shotType: "Defensive" },
    ],
    deliveries: []
  },
  {
    id: "j-bumrah",
    name: "Jasprit Bumrah",
    team: "India",
    role: "bowler",
    style: "Right-arm Fast",
    type: "bowler",
    matches: [
      { id: "b1", opponent: "Pakistan", date: "2024-10-23", matchType: "T20", overs: 4, runsConceded: 14, wickets: 3, maidens: 1, dots: 16 },
      { id: "b2", opponent: "England", date: "2024-11-10", matchType: "ODI", overs: 10, runsConceded: 32, wickets: 4, maidens: 2, dots: 42 },
      { id: "b3", opponent: "Australia", date: "2025-01-18", matchType: "Test", overs: 8, runsConceded: 28, wickets: 2, maidens: 0, dots: 28 },
      { id: "b4", opponent: "New Zealand", date: "2025-02-05", matchType: "Test", overs: 6, runsConceded: 22, wickets: 1, maidens: 1, dots: 20 },
      { id: "b5", opponent: "South Africa", date: "2025-03-24", matchType: "ODI", overs: 9, runsConceded: 30, wickets: 3, maidens: 1, dots: 32 },
    ],
    shots: [],
    deliveries: [
      { id: "d1", x: 50, y: 10, lengthType: "Yorker", lineType: "On the Stumps", runsConceded: 0, isWicket: true },
      { id: "d2", x: 52, y: 12, lengthType: "Yorker", lineType: "On the Stumps", runsConceded: 0, isWicket: true },
      { id: "d3", x: 62, y: 55, lengthType: "Good Length", lineType: "Outside Off", runsConceded: 1, isWicket: false },
      { id: "d4", x: 65, y: 58, lengthType: "Good Length", lineType: "Outside Off", runsConceded: 0, isWicket: false },
      { id: "d5", x: 35, y: 85, lengthType: "Short Pitch", lineType: "Down Leg", runsConceded: 4, isWicket: false },
      { id: "d6", x: 51, y: 62, lengthType: "Good Length", lineType: "On the Stumps", runsConceded: 0, isWicket: true },
      { id: "d7", x: 60, y: 22, lengthType: "Full Pitch", lineType: "Outside Off", runsConceded: 4, isWicket: false },
      { id: "d8", x: 48, y: 58, lengthType: "Good Length", lineType: "On the Stumps", runsConceded: 1, isWicket: false },
      { id: "d9", x: 54, y: 80, lengthType: "Short Pitch", lineType: "On the Stumps", runsConceded: 1, isWicket: false },
      { id: "d10", x: 68, y: 52, lengthType: "Good Length", lineType: "Outside Off", runsConceded: 0, isWicket: false },
    ]
  },
  {
    id: "r-khan",
    name: "Rashid Khan",
    team: "Afghanistan",
    role: "allrounder",
    style: "Right-arm Leg Spin",
    type: "bowler",
    matches: [
      { id: "bb1", opponent: "Pakistan", date: "2024-10-25", matchType: "T20", overs: 4, runsConceded: 20, wickets: 2, maidens: 0, dots: 12 },
      { id: "bb2", opponent: "England", date: "2024-11-12", matchType: "ODI", overs: 10, runsConceded: 45, wickets: 3, maidens: 1, dots: 28 },
      { id: "bb3", opponent: "Australia", date: "2025-01-22", matchType: "ODI", overs: 10, runsConceded: 52, wickets: 1, maidens: 0, dots: 25 },
      { id: "bb4", opponent: "New Zealand", date: "2025-02-08", matchType: "Test", overs: 8, runsConceded: 38, wickets: 2, maidens: 0, dots: 22 },
      { id: "bb5", opponent: "South Africa", date: "2025-03-28", matchType: "T20", overs: 4, runsConceded: 16, wickets: 2, maidens: 1, dots: 14 },
    ],
    shots: [],
    deliveries: [
      { id: "rd1", x: 58, y: 65, lengthType: "Good Length", lineType: "On the Stumps", runsConceded: 0, isWicket: true },
      { id: "rd2", x: 62, y: 68, lengthType: "Good Length", lineType: "Outside Off", runsConceded: 1, isWicket: false },
      { id: "rd3", x: 45, y: 30, lengthType: "Full Pitch", lineType: "On the Stumps", runsConceded: 6, isWicket: false },
      { id: "rd4", x: 54, y: 60, lengthType: "Good Length", lineType: "On the Stumps", runsConceded: 0, isWicket: true },
      { id: "rd5", x: 38, y: 88, lengthType: "Short Pitch", lineType: "Down Leg", runsConceded: 4, isWicket: false },
      { id: "rd6", x: 50, y: 15, lengthType: "Yorker", lineType: "On the Stumps", runsConceded: 1, isWicket: false },
      { id: "rd7", x: 59, y: 61, lengthType: "Good Length", lineType: "On the Stumps", runsConceded: 0, isWicket: true },
    ]
  }
];
